### ISSUE TITLE
Doesn't work with xcode 11 projects

### ISSUE THREAD

**Issue by Gargo** [sarojraut/SRActivityIndicator#3]
```
self.center = (delegate!.window!?.rootViewController?.view.center)!
```
looks AWFUL!
+ it doesn't work at all for new xcode 11 projects when app delegate doesn't have `window` because there are scenes added. `window` property is optional but you force unwrap it to non-nil value

**Comment by sarojraut** [comment]
Scenes are only used for IOS 13 or newer projects. This work for IOS 10 or later. you can add   
 var window: UIWindow?
in your appdelegate if you want to support IOS version lower than 13.
